// AUTO-GENERATED by Editmamei/scripts/sync-changelogs.ts — do NOT edit
// directly. Re-run `npm run sync:changelogs` in the Editmamei repo to
// regenerate this file from Editmamei/CHANGELOG.md.
//
// The canonical changelog lives at Editmamei/CHANGELOG.md (private source
// repo). The CE mirror at editmamei-ce/CHANGELOG.md is the public version
// linked from `fullChangelogUrl` below.

export interface ChangelogEntry {
	label: string;
	date: string;
	title: string;
	body: string;
}

export const changelogEntries: ChangelogEntry[] = [
	{
		label: "v0.4.2",
		date: "2026-06",
		title: "Layer-to-group moves no longer fail with a syntax error",
		body: "Every move-into-group call had been failing with a Photoshop parse error; the fix lets em-dash normalization work as originally intended."
	},
	{
		label: "v0.4.1",
		date: "2026-06",
		title: "Group memberships handle Unicode dash variants",
		body: "Creating a group from a list of layer names now matches em-dash, en-dash, and ASCII hyphen-minus the same way move and select tools already did."
	},
	{
		label: "v0.4.0",
		date: "2026-06",
		title: "Place Image gets non-uniform scale",
		body: "Optional width and height percent parameters let you stretch a placed Smart Object instead of being locked to its native size."
	},
	{
		label: "v0.4.0",
		date: "2026-06",
		title: "Levels adjustment honors black/white/gamma on PS 27.x",
		body: "Three silent-no-op drifts in the post-create descriptor were dropping user-set tonal values; the fix means setting input black / white / gamma actually takes effect."
	},
	{
		label: "v0.4.0",
		date: "2026-06",
		title: "Invert adjustment layer uses the captured PS UI form",
		body: "Mk path now uses putClass(Type, Invr) with no inner descriptor; previously coerced PS into an unexpected creation path with putObject + presetKindDefault."
	},
	{
		label: "v0.4.0",
		date: "2026-06",
		title: "Outer Glow range slider type fix",
		body: "The Range slider on Outer Glow layer styles was sending a putInteger where PS wants a unitDouble percentUnit, silently default-falling back to the wrong behavior."
	}
];

export const fullChangelogUrl = 'https://github.com/editmamei/editmamei-ce/blob/main/CHANGELOG.md';
