// AUTO-GENERATED by Editmamei/scripts/sync-changelogs.ts — do NOT edit
// directly. Re-run `npm run sync:changelogs` in the Editmamei repo to
// regenerate this file from Editmamei/CHANGELOG.md.
//
// The canonical changelog lives at Editmamei/CHANGELOG.md (private source
// repo). The CE mirror at editmamei-ce/CHANGELOG.md is the public version
// linked from `fullChangelogUrl` below.

export interface ChangelogEntry {
	label: string;
	date: string;
	title: string;
	body: string;
}

export const changelogEntries: ChangelogEntry[] = [
	{
		label: "v0.5.5",
		date: "2026-06",
		title: "Previews are reliable on macOS again",
		body: "Two preview calls in the same Mac session failed with an ENOENT error on the temp file under /tmp, while other previews in the same session worked."
	},
	{
		label: "v0.5.4",
		date: "2026-06",
		title: "Mask creation no longer fails after a chain of selection tools on macOS Photoshop 27.7",
		body: "A fresh-install v0.5.3 Mac session reproduced the original v0.5.2 bug class: the first mask creation in a session worked, but a second attempt after multiple selection tool calls failed with the \"command Make not currently available\" error."
	},
	{
		label: "v0.5.3",
		date: "2026-06",
		title: "Smart selection tools no longer leave the document on a non-composite channel when they fail",
		body: "v0.5.2 fixed the normal-return path; an audit follow-up found the same bug class on every smart-selection tool's *failure* path."
	},
	{
		label: "v0.5.3",
		date: "2026-06",
		title: "Stamp Visible — the Ctrl+Alt+Shift+E shortcut as a first-class tool",
		body: "Merges all currently-visible layers into a NEW layer placed above the active layer, leaving the originals untouched."
	},
	{
		label: "v0.5.3",
		date: "2026-06",
		title: "`restoreCompositeChannel` no longer adds a redundant \"Select RGB Channel\" undo entry on the common case",
		body: "A QA finding on v0.5.2 noted that the channel-restore helper was firing the slct AM event unconditionally — adding a cosmetic history entry every time a selection tool finished, even when Photoshop had already fallen back to composite on its own."
	},
	{
		label: "v0.5.2",
		date: "2026-06",
		title: "Mask creation now works after smart-selection and selection-preview steps",
		body: "A canonical \"isolate the subject\" flow (smart selection → review the selection → feather it → make a mask) was failing on the final step with a generic Photoshop error."
	}
];

export const fullChangelogUrl = 'https://github.com/editmamei/editmamei-ce/blob/main/CHANGELOG.md';
