// AUTO-GENERATED by Editmamei/scripts/sync-changelogs.ts — do NOT edit
// directly. Re-run `npm run sync:changelogs` in the Editmamei repo to
// regenerate this file from Editmamei/CHANGELOG.md.
//
// The canonical changelog lives at Editmamei/CHANGELOG.md (private source
// repo). The CE mirror at editmamei-ce/CHANGELOG.md is the public version
// linked from `fullChangelogUrl` below.

export interface ChangelogEntry {
	label: string;
	date: string;
	title: string;
	body: string;
}

export const changelogEntries: ChangelogEntry[] = [
	{
		label: "v0.4.3",
		date: "2026-06",
		title: "Luminosity histograms now work",
		body: "The schema's channel: 'luminosity' enum value was advertised but every call failed with \"Channel not found: luminosity\" because the snippet did a name lookup in doc.channels (which on RGB documents only contains Red/Green/Blue)."
	},
	{
		label: "v0.4.3",
		date: "2026-06",
		title: "Composite histograms no longer fail after an adjustment layer is added",
		body: "doc.histogram returns \"The requested property does not exist\" in PS 27.x whenever the active layer is an adjustment, fill, or shape layer — meaning every composite read after add_adjustment_layer failed."
	},
	{
		label: "v0.4.3",
		date: "2026-06",
		title: "Histogram tool description now matches reality",
		body: "Spells out the per-mode luminosity dispatch, the Rec.709 approximation on RGB, and the adjustment-layer composite-recovery so the LLM can pick the right channel without guessing."
	},
	{
		label: "v0.4.2",
		date: "2026-06",
		title: "Layer-to-group moves no longer fail with a syntax error",
		body: "Every move-into-group call had been failing with a Photoshop parse error; the fix lets em-dash normalization work as originally intended."
	},
	{
		label: "v0.4.1",
		date: "2026-06",
		title: "Group memberships handle Unicode dash variants",
		body: "Creating a group from a list of layer names now matches em-dash, en-dash, and ASCII hyphen-minus the same way move and select tools already did."
	},
	{
		label: "v0.4.0",
		date: "2026-06",
		title: "Place Image gets non-uniform scale",
		body: "Optional width and height percent parameters let you stretch a placed Smart Object instead of being locked to its native size."
	}
];

export const fullChangelogUrl = 'https://github.com/editmamei/editmamei-ce/blob/main/CHANGELOG.md';
